apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: akp-tmp
  name: akp-tmp-svc
spec:
  ports:
  - port: 4444
    protocol: TCP
    targetPort: 80
  selector:
    run: akp-tmp
status:
  loadBalancer: {}
