apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: simple-pod
  name: simple-pod
spec:
  containers:
  - image: nginx
    name: simple-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}