apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: akp-tmp
  name: akp-tmp
spec:
  containers:
  - image: nginx:alpine
    name: akp-tmp
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
